export interface ApiResponseReturn<T = unknown> {
  status: number
  response: T
  [key: string]: unknown
}

export interface ApiResponseOptions<T = unknown> {
  response: T
  status: number
  metadata?: Record<string, unknown>
}

export const ErrorCode = {
  TOKEN_DEPOSIT_DISABLED: 'TOKEN_DEPOSIT_DISABLED',
  TOKEN_NOT_REGISTERED: 'TOKEN_NOT_REGISTERED',
  TOKEN_NOT_APPROVED: 'TOKEN_NOT_APPROVED',
  INSUFFICIENT_L1_ETH: 'INSUFFICIENT_L1_ETH',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  GATEWAY_FETCH_FAILED: 'GATEWAY_FETCH_FAILED',
  REGISTRATION_CHECK_FAILED: 'REGISTRATION_CHECK_FAILED',
  DEPOSIT_DISABLED_CHECK_FAILED: 'DEPOSIT_DISABLED_CHECK_FAILED',
  BALANCE_CHECK_FAILED: 'BALANCE_CHECK_FAILED',
  BRIDGE_REQUEST_FAILED: 'BRIDGE_REQUEST_FAILED',
  INVALID_CHAIN_PAIR: 'INVALID_CHAIN_PAIR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
